name: resistance_app
description: Control Wahoo Kickr Core 2 trainer resistance via Bluetooth
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.0
  shared_preferences: ^2.3.0
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.2.1
  health: ^11.1.0
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
